CREATE TABLE USER
(
USER_EMAIL   VARCHAR(100)    NOT NULL,
USER_PASSWORD   VARCHAR(100),
USER_SCHOOL  VARCHAR(100),
USER_YEAR    INT(4),
USER_ROLE VARCHAR(20),
USER_FUND    DOUBLE,
CONSTRAINT USER_PK PRIMARY KEY (USER_EMAIL)
);

CREATE TABLE ROOM
(
ROOM_ID VARCHAR(100)    NOT NULL,
ROOM_FLAT_RATE   DOUBLE,
ROOM_CAPACITY    INT(3),
ROOM_SCHOOL VARCHAR(100),
ROOM_TYPE   VARCHAR(100),
ROOM_FLOOR  INT(2),
ROOM_NUMBER VARCHAR(100),
CONSTRAINT ROOM_PK PRIMARY KEY(ROOM_ID)
);

CREATE TABLE NOTIFICATION
(
NOTIFICATION_DATETIME   DATETIME    NOT NULL,
NOTIFICATION_MESSAGE    TEXT,
NOTIFICATION_USER_EMAIL VARCHAR(100) ,
CONSTRAINT NOTIFICATION_PK PRIMARY KEY (NOTIFICATION_DATETIME),
CONSTRAINT NOTIFICATION_FK FOREIGN KEY (NOTIFICATION_USER_EMAIL) REFERENCES USER(USER_EMAIL)
);

CREATE TABLE BOOKING
(
BOOKING_REFERENCE_ID    VARCHAR(100)    NOT NULL,
BOOKING_USER_EMAIL  VARCHAR(100)    NOT NULL,
BOOKING_ROOM_ID VARCHAR(100)    NOT NULL,
BOOKING_START_DATE  DATE    NOT NULL,
BOOKING_START_TIME  TIME    NOT NULL,
BOOKING_END_DATE  DATE,
BOOKING_END_TIME  TIME,
BOOKING_PURPOSE TEXT,
BOOKING_TERMINATED  VARCHAR(100),
BOOKING_RECURRING   VARCHAR(100),
CONSTRAINT BOOKING_PK1 PRIMARY KEY (BOOKING_REFERENCE_ID,BOOKING_USER_EMAIL,
BOOKING_ROOM_ID,BOOKING_START_DATE,BOOKING_START_TIME),
CONSTRAINT BOOKING_FK1 FOREIGN KEY (BOOKING_USER_EMAIL) REFERENCES USER(USER_EMAIL),
CONSTRAINT BOOKING_FK2 FOREIGN KEY (BOOKING_ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
